//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.MvcCall {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MvcCall.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/IsValid", ReplyAction="http://tempuri.org/IAdminService/IsValidResponse")]
        bool IsValid(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/IsValid", ReplyAction="http://tempuri.org/IAdminService/IsValidResponse")]
        System.Threading.Tasks.Task<bool> IsValidAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/CreateAdmin", ReplyAction="http://tempuri.org/IAdminService/CreateAdminResponse")]
        bool CreateAdmin(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/CreateAdmin", ReplyAction="http://tempuri.org/IAdminService/CreateAdminResponse")]
        System.Threading.Tasks.Task<bool> CreateAdminAsync(string obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : Fantasy.MvcCall.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<Fantasy.MvcCall.IAdminService>, Fantasy.MvcCall.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsValid(string user, string password) {
            return base.Channel.IsValid(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidAsync(string user, string password) {
            return base.Channel.IsValidAsync(user, password);
        }
        
        public bool CreateAdmin(string obj) {
            return base.Channel.CreateAdmin(obj);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAdminAsync(string obj) {
            return base.Channel.CreateAdminAsync(obj);
        }
    }
}
